const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
const endpointsFiles = ['./src/index.js']
const doc = {
    info: {
        version: "1.0.0",
        title: "Chat APP",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8080",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    securityDefinitions: {
        apiKeyAuth:{
            type: "apiKey",
            in: "header",
            name: "Authorization",
            description: "Auth Token"
        }
    },
    definitions: {
        Errors: {
            errors: {
                message: 'string',
                errCode: 'string'
            }
        },
        User: {
            id: 1,
            name: 'Joe doe',
            "email": "teste@email.com",
            "createdAt": "2021-03-23T16:58:30.000Z"
        },
        Room: {
            id: 1,
            name: 'Joe doe',
            description: "Descricao da sala",
            owner_id: 1,
            user_to_id: 2,
            "createdAt": "2021-03-23T16:58:30.000Z"
        },
        Rooms: [ 
            { $ref: "#/definitions/Room" }
        ],
        Message: {
            id: 1,
            name: 'Joe doe',
            "email": "teste@email.com",
            "createdAt": "2021-03-23T16:58:30.000Z"
        },
        Messages: [ 
            { $ref: "#/definitions/Message" }
        ]

    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then( () => {
	require('./src/index.js')
})